package com.example.hello;

/**
 * Stub R class for HelloActivity compilation.
 * In a real APK, this is auto-generated by aapt from resources.
 */
public final class R {
    public static final class layout {
        public static final int activity_main = 0x7f030000;
    }
    public static final class string {
        public static final int app_name = 0x7f020000;
        public static final int greeting = 0x7f020001;
    }
}
