-- Known mappings for android.graphics.Paint, android.graphics.Canvas,
-- android.graphics.Matrix, and android.os.Parcel
-- Generated 2026-03-13
--
-- Paint → OH_Drawing_Pen (stroke) + OH_Drawing_Brush (fill) via NDK
-- Canvas → OH_Drawing_Canvas via NDK
-- Matrix → OH_Drawing_Matrix via NDK
-- Parcel → @ohos.rpc MessageSequence

-- ============================================================
-- BATCH 1: Paint (methods 1-50)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.graphics', 'Paint', 'Paint', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenCreate', 8.0, 'Constructor; OH splits Paint into Pen (stroke) + Brush (fill)', 1),
  ('android.graphics', 'Paint', 'reset', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenDestroy+PenCreate', 6.0, 'No direct reset; destroy and recreate', 0),
  ('android.graphics', 'Paint', 'set', 'native_drawing', 'OH_Drawing_Pen', NULL, 5.0, 'Copy all properties manually; no single copy function', 0),
  ('android.graphics', 'Paint', 'setFlags', 'native_drawing', 'OH_Drawing_Pen', NULL, 4.0, 'No flags concept; map individual flags to Pen/Brush properties', 0),
  ('android.graphics', 'Paint', 'getFlags', 'native_drawing', 'OH_Drawing_Pen', NULL, 4.0, 'No flags concept; reconstruct from individual properties', 0),
  ('android.graphics', 'Paint', 'setAntiAlias', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetAntiAlias', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'isAntiAlias', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenIsAntiAlias', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setDither', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Dithering not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'isDither', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Dithering not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'setLinearText', 'native_drawing', 'OH_Drawing_Font', 'OH_Drawing_FontSetLinearText', 7.0, 'Mapped via OH_Drawing_Font not Pen', 0),
  ('android.graphics', 'Paint', 'isLinearText', 'native_drawing', 'OH_Drawing_Font', NULL, 5.0, 'No getter in OH Drawing Font', 0),
  ('android.graphics', 'Paint', 'setSubpixelText', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Subpixel text not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'isSubpixelText', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Subpixel text not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'setUnderlineText', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleDecoration', 7.0, 'Via Typography text decoration', 0),
  ('android.graphics', 'Paint', 'isUnderlineText', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 5.0, 'Check decoration flags', 0),
  ('android.graphics', 'Paint', 'setStrikeThruText', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleDecoration', 7.0, 'Via Typography text decoration', 0),
  ('android.graphics', 'Paint', 'isStrikeThruText', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 5.0, 'Check decoration flags', 0),
  ('android.graphics', 'Paint', 'setFakeBoldText', 'native_drawing', 'OH_Drawing_Font', 'OH_Drawing_FontSetFakeBoldText', 8.0, 'Direct mapping via Font', 0),
  ('android.graphics', 'Paint', 'isFakeBoldText', 'native_drawing', 'OH_Drawing_Font', NULL, 5.0, 'No getter in OH Drawing Font', 0),
  ('android.graphics', 'Paint', 'setFilterBitmap', 'native_drawing', 'OH_Drawing_Filter', 'OH_Drawing_FilterCreate', 6.0, 'Use OH_Drawing_Filter for bitmap filtering', 0),
  ('android.graphics', 'Paint', 'isFilterBitmap', 'native_drawing', 'OH_Drawing_Filter', NULL, 5.0, 'No direct getter', 0),
  ('android.graphics', 'Paint', 'setStyle', 'native_drawing', 'OH_Drawing_Pen', NULL, 7.0, 'STROKE→attach Pen; FILL→attach Brush; FILL_AND_STROKE→both', 1),
  ('android.graphics', 'Paint', 'getStyle', 'native_drawing', 'OH_Drawing_Pen', NULL, 5.0, 'Must track locally; OH has separate Pen/Brush model', 1),
  ('android.graphics', 'Paint', 'setColor', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetColor', 9.0, 'Direct mapping; also set on Brush', 0),
  ('android.graphics', 'Paint', 'getColor', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetColor', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setAlpha', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetAlpha', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'getAlpha', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetAlpha', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setARGB', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetColor', 8.0, 'Compose ARGB then call PenSetColor', 0),
  ('android.graphics', 'Paint', 'setStrokeWidth', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetWidth', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'getStrokeWidth', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetWidth', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setStrokeMiter', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetMiterLimit', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'getStrokeMiter', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetMiterLimit', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setStrokeCap', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetCap', 9.0, 'Direct; map Cap enum to OH_Drawing_PenLineCapStyle', 0),
  ('android.graphics', 'Paint', 'getStrokeCap', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetCap', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setStrokeJoin', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetJoin', 9.0, 'Direct; map Join enum to OH_Drawing_PenLineJoinStyle', 0),
  ('android.graphics', 'Paint', 'getStrokeJoin', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenGetJoin', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Paint', 'setShader', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenSetShaderEffect', 8.0, 'Map Shader subclass to OH_Drawing_ShaderEffect', 0),
  ('android.graphics', 'Paint', 'getShader', 'native_drawing', 'OH_Drawing_Pen', NULL, 4.0, 'No getter for shader effect in OH NDK', 0),
  ('android.graphics', 'Paint', 'setColorFilter', 'native_drawing', 'OH_Drawing_Filter', 'OH_Drawing_FilterSetColorFilter', 8.0, 'Via OH_Drawing_Filter + OH_Drawing_ColorFilter', 0),
  ('android.graphics', 'Paint', 'getColorFilter', 'native_drawing', 'OH_Drawing_Filter', NULL, 4.0, 'No getter for color filter in OH NDK', 0),
  ('android.graphics', 'Paint', 'setXfermode', 'native_drawing', 'OH_Drawing_Pen', NULL, 5.0, 'Use OH_Drawing_BlendMode; set via blend mode APIs', 0),
  ('android.graphics', 'Paint', 'getXfermode', 'native_drawing', 'OH_Drawing_Pen', NULL, 4.0, 'No direct getter', 0),
  ('android.graphics', 'Paint', 'setPathEffect', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'PathEffect not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getPathEffect', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'PathEffect not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'setMaskFilter', 'native_drawing', 'OH_Drawing_Filter', 'OH_Drawing_FilterSetMaskFilter', 8.0, 'Via OH_Drawing_Filter + OH_Drawing_MaskFilter', 0),
  ('android.graphics', 'Paint', 'getMaskFilter', 'native_drawing', 'OH_Drawing_Filter', NULL, 4.0, 'No getter for mask filter in OH NDK', 0),
  ('android.graphics', 'Paint', 'setTypeface', 'native_drawing', 'OH_Drawing_Font', 'OH_Drawing_FontSetTypeface', 8.0, 'Via OH_Drawing_Font', 0),
  ('android.graphics', 'Paint', 'getTypeface', 'native_drawing', 'OH_Drawing_Font', NULL, 4.0, 'No getter for typeface in OH Drawing Font', 0),
  ('android.graphics', 'Paint', 'setShadowLayer', 'native_drawing', 'OH_Drawing_Filter', NULL, 3.0, 'No shadow layer in OH Drawing NDK; use filter or custom', 0),
  ('android.graphics', 'Paint', 'clearShadowLayer', 'native_drawing', 'OH_Drawing_Filter', NULL, 3.0, 'No shadow layer in OH Drawing NDK', 0);

-- ============================================================
-- BATCH 2: Paint (methods 51-107)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.graphics', 'Paint', 'setTextAlign', 'native_drawing', 'OH_Drawing_TypographyStyle', 'OH_Drawing_SetTypographyTextAlign', 7.0, 'Text alignment via Typography', 0),
  ('android.graphics', 'Paint', 'getTextAlign', 'native_drawing', 'OH_Drawing_TypographyStyle', NULL, 5.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setTextLocale', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleLocale', 8.0, 'Direct mapping via TextStyle', 0),
  ('android.graphics', 'Paint', 'getTextLocale', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 5.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setTextLocales', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleLocale', 6.0, 'OH supports single locale; use first', 0),
  ('android.graphics', 'Paint', 'getTextLocales', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 4.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setElegantTextHeight', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleFontHeight', 6.0, 'Approximate via font height', 0),
  ('android.graphics', 'Paint', 'isElegantTextHeight', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 4.0, 'No direct equivalent', 0),
  ('android.graphics', 'Paint', 'setTextSize', 'native_drawing', 'OH_Drawing_Font', 'OH_Drawing_FontSetTextSize', 9.0, 'Direct mapping via Font', 0),
  ('android.graphics', 'Paint', 'getTextSize', 'native_drawing', 'OH_Drawing_Font', NULL, 5.0, 'No getter in OH Drawing Font', 0),
  ('android.graphics', 'Paint', 'setTextScaleX', 'native_drawing', 'OH_Drawing_Font', NULL, 3.0, 'No text scale X in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getTextScaleX', 'native_drawing', 'OH_Drawing_Font', NULL, 3.0, 'No text scale X in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'setTextSkewX', 'native_drawing', 'OH_Drawing_Font', 'OH_Drawing_FontSetTextSkewX', 9.0, 'Direct mapping via Font', 0),
  ('android.graphics', 'Paint', 'getTextSkewX', 'native_drawing', 'OH_Drawing_Font', NULL, 5.0, 'No getter in OH Drawing Font', 0),
  ('android.graphics', 'Paint', 'setLetterSpacing', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleLetterSpacing', 8.0, 'Via Typography TextStyle', 0),
  ('android.graphics', 'Paint', 'getLetterSpacing', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 5.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setWordSpacing', 'native_drawing', 'OH_Drawing_TextStyle', 'OH_Drawing_SetTextStyleWordSpacing', 8.0, 'Via Typography TextStyle', 0),
  ('android.graphics', 'Paint', 'getWordSpacing', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 5.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setFontFeatureSettings', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 3.0, 'Font features not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'getFontFeatureSettings', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 3.0, 'Font features not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'setFontVariationSettings', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 3.0, 'Font variations not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'getFontVariationSettings', 'native_drawing', 'OH_Drawing_TextStyle', NULL, 3.0, 'Font variations not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'ascent', 'native_drawing', 'OH_Drawing_Typography', 'OH_Drawing_TypographyGetAlphabeticBaseline', 6.0, 'Approximate; use typography metrics', 0),
  ('android.graphics', 'Paint', 'descent', 'native_drawing', 'OH_Drawing_Typography', 'OH_Drawing_TypographyGetIdeographicBaseline', 6.0, 'Approximate; use typography metrics', 0),
  ('android.graphics', 'Paint', 'getFontMetrics', 'native_drawing', 'OH_Drawing_Typography', NULL, 5.0, 'Compute from typography baselines and height', 0),
  ('android.graphics', 'Paint', 'getFontMetricsInt', 'native_drawing', 'OH_Drawing_Typography', NULL, 5.0, 'Compute from typography baselines and height; cast to int', 0),
  ('android.graphics', 'Paint', 'getFontSpacing', 'native_drawing', 'OH_Drawing_Typography', 'OH_Drawing_TypographyGetLineHeight', 7.0, 'Line height approximates font spacing', 0),
  ('android.graphics', 'Paint', 'measureText', 'native_drawing', 'OH_Drawing_Typography', 'OH_Drawing_TypographyGetMaxIntrinsicWidth', 7.0, 'Layout single line then get width', 0),
  ('android.graphics', 'Paint', 'breakText', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'No direct equivalent; use typography layout with max width', 0),
  ('android.graphics', 'Paint', 'getTextWidths', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'No per-char widths; use glyph position API', 0),
  ('android.graphics', 'Paint', 'getTextPath', 'native_drawing', 'OH_Drawing_Path', NULL, 3.0, 'No text-to-path in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getTextBounds', 'native_drawing', 'OH_Drawing_Typography', NULL, 5.0, 'Use typography layout then get rects for range', 0),
  ('android.graphics', 'Paint', 'hasGlyph', 'native_drawing', 'OH_Drawing_Font', NULL, 3.0, 'No glyph check in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getRunAdvance', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'Use glyph position APIs', 0),
  ('android.graphics', 'Paint', 'getOffsetForAdvance', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'Use glyph position APIs', 0),
  ('android.graphics', 'Paint', 'setHinting', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Hinting not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getHinting', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'Hinting not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'setBlendMode', 'native_drawing', 'OH_Drawing_Pen', NULL, 6.0, 'OH_Drawing_BlendMode enum exists; set via brush/pen', 0),
  ('android.graphics', 'Paint', 'getBlendMode', 'native_drawing', 'OH_Drawing_Pen', NULL, 4.0, 'No getter; track locally', 0),
  ('android.graphics', 'Paint', 'setTextRunShaper', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'No direct equivalent in OH NDK', 0),
  ('android.graphics', 'Paint', 'setColorLong', 'native_drawing', 'OH_Drawing_Brush', 'OH_Drawing_BrushSetColor', 8.0, 'setColor(long) variant; set on Brush for fill', 0),
  ('android.graphics', 'Paint', 'setStartHyphenEdit', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'Hyphenation not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'setEndHyphenEdit', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'Hyphenation not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'getStartHyphenEdit', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'Hyphenation not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'getEndHyphenEdit', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'Hyphenation not exposed in OH NDK', 0),
  ('android.graphics', 'Paint', 'getFillPath', 'native_drawing', 'OH_Drawing_Path', NULL, 3.0, 'No fill-path extraction in OH NDK', 0),
  ('android.graphics', 'Paint', 'getStrokePath', 'native_drawing', 'OH_Drawing_Path', NULL, 3.0, 'No stroke-path extraction in OH NDK', 0),
  ('android.graphics', 'Paint', 'nativeGetRunCharacterAdvance', 'native_drawing', 'OH_Drawing_Typography', NULL, 3.0, 'Internal native; use glyph APIs', 0),
  ('android.graphics', 'Paint', 'equalsForTextMeasurement', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'No direct equivalent; compare properties manually', 0),
  ('android.graphics', 'Paint', 'getTextRunCursor', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'Use word boundary and glyph position APIs', 0),
  ('android.graphics', 'Paint', 'getTextRunAdvances', 'native_drawing', 'OH_Drawing_Typography', NULL, 4.0, 'Use glyph position APIs', 0),
  ('android.graphics', 'Paint', 'setCompatibilityScaling', 'native_drawing', 'OH_Drawing_Pen', NULL, 3.0, 'No compat scaling in OH NDK', 0),
  ('android.graphics', 'Paint', 'finalize', 'native_drawing', 'OH_Drawing_Pen', 'OH_Drawing_PenDestroy', 8.0, 'Destroy pen and brush', 0),
  ('android.graphics', 'Paint', 'setFilterQuality', 'native_drawing', 'OH_Drawing_Filter', 'OH_Drawing_FilterCreate', 6.0, 'Use filter mechanism', 0),
  ('android.graphics', 'Paint', 'getFilterQuality', 'native_drawing', 'OH_Drawing_Filter', NULL, 4.0, 'No direct getter', 0),
  ('android.graphics', 'Paint', 'setImageFilter', 'native_drawing', 'OH_Drawing_Filter', NULL, 3.0, 'Image filter not exposed in OH Drawing NDK', 0),
  ('android.graphics', 'Paint', 'getImageFilter', 'native_drawing', 'OH_Drawing_Filter', NULL, 3.0, 'Image filter not exposed in OH Drawing NDK', 0);

-- ============================================================
-- BATCH 3: Canvas (methods 1-50)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.graphics', 'Canvas', 'Canvas', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasCreate', 9.0, 'Constructor', 0),
  ('android.graphics', 'Canvas', 'isOpaque', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No opacity check in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'getWidth', 'native_drawing', 'OH_Drawing_Bitmap', 'OH_Drawing_BitmapGetWidth', 7.0, 'Get from bound bitmap', 0),
  ('android.graphics', 'Canvas', 'getHeight', 'native_drawing', 'OH_Drawing_Bitmap', 'OH_Drawing_BitmapGetHeight', 7.0, 'Get from bound bitmap', 0),
  ('android.graphics', 'Canvas', 'getDensity', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No density concept in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'setDensity', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No density concept in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'save', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasSave', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'saveLayer', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasSave', 6.0, 'OH save does not support layer bounds/alpha; approximate', 0),
  ('android.graphics', 'Canvas', 'saveLayerAlpha', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasSave', 5.0, 'OH save does not support alpha layers', 0),
  ('android.graphics', 'Canvas', 'restore', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasRestore', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'getSaveCount', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasGetSaveCount', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'restoreToCount', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasRestoreToCount', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'translate', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasTranslate', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'scale', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasScale', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'rotate', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasRotate', 9.0, 'Direct mapping; OH version takes pivot point', 0),
  ('android.graphics', 'Canvas', 'skew', 'native_drawing', 'OH_Drawing_Canvas', NULL, 4.0, 'No skew in OH Drawing Canvas; use matrix concat', 0),
  ('android.graphics', 'Canvas', 'concat', 'native_drawing', 'OH_Drawing_Canvas', NULL, 5.0, 'No direct concat; build matrix and apply', 0),
  ('android.graphics', 'Canvas', 'setMatrix', 'native_drawing', 'OH_Drawing_Canvas', NULL, 5.0, 'No setMatrix; use save/restore + matrix ops', 0),
  ('android.graphics', 'Canvas', 'getMatrix', 'native_drawing', 'OH_Drawing_Canvas', NULL, 4.0, 'No getMatrix in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'clipRect', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClipRect', 9.0, 'Direct; supports ClipOp and antiAlias', 0),
  ('android.graphics', 'Canvas', 'clipPath', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClipPath', 9.0, 'Direct; supports ClipOp and antiAlias', 0),
  ('android.graphics', 'Canvas', 'clipOutRect', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClipRect', 8.0, 'Use DIFFERENCE ClipOp', 0),
  ('android.graphics', 'Canvas', 'clipOutPath', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClipPath', 8.0, 'Use DIFFERENCE ClipOp', 0),
  ('android.graphics', 'Canvas', 'getClipBounds', 'native_drawing', 'OH_Drawing_Canvas', NULL, 4.0, 'No clip bounds getter in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'quickReject', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No quick reject in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawRGB', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClear', 7.0, 'Clear with composed RGB color', 0),
  ('android.graphics', 'Canvas', 'drawARGB', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClear', 8.0, 'Clear with composed ARGB color', 0),
  ('android.graphics', 'Canvas', 'drawColor', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClear', 8.0, 'Direct mapping (clear fills entire canvas)', 0),
  ('android.graphics', 'Canvas', 'drawPaint', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasClear', 6.0, 'Approximate: clear with paint color', 0),
  ('android.graphics', 'Canvas', 'drawPoints', 'native_drawing', 'OH_Drawing_Canvas', NULL, 4.0, 'No drawPoints in OH NDK; draw individual lines of zero length', 0),
  ('android.graphics', 'Canvas', 'drawPoint', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawLine', 6.0, 'Draw zero-length line at point', 0),
  ('android.graphics', 'Canvas', 'drawLine', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawLine', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawLines', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawLine', 7.0, 'Call DrawLine in a loop', 0),
  ('android.graphics', 'Canvas', 'drawRect', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawRect', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawOval', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawOval', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawCircle', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawCircle', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawArc', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawArc', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawRoundRect', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawRoundRect', 9.0, 'Direct mapping via OH_Drawing_RoundRect', 0),
  ('android.graphics', 'Canvas', 'drawPath', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawPath', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawBitmap', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawBitmap', 9.0, 'Direct mapping', 0),
  ('android.graphics', 'Canvas', 'drawBitmapMesh', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No bitmap mesh in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawVertices', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No vertex drawing in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawText', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawTextBlob', 8.0, 'Build TextBlob from text then draw', 0),
  ('android.graphics', 'Canvas', 'drawTextOnPath', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No text-on-path in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawTextRun', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawTextBlob', 6.0, 'Build TextBlob then draw; complex text shaping needed', 0),
  ('android.graphics', 'Canvas', 'drawPosText', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawTextBlob', 5.0, 'Deprecated; build positioned TextBlob', 0),
  ('android.graphics', 'Canvas', 'drawPicture', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No Picture recording in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'isHardwareAccelerated', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No hardware acceleration query in OH NDK', 0),
  ('android.graphics', 'Canvas', 'enableZ', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No Z-ordering in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'disableZ', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No Z-ordering in OH Drawing NDK', 0);

-- ============================================================
-- BATCH 4: Canvas (methods 51-68)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.graphics', 'Canvas', 'drawDoubleRoundRect', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No double round rect in OH Drawing NDK; use path', 0),
  ('android.graphics', 'Canvas', 'drawRenderNode', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No RenderNode concept in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawGlyphs', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawTextBlob', 5.0, 'Build TextBlob with glyph IDs', 0),
  ('android.graphics', 'Canvas', 'setBitmap', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasBind', 8.0, 'Bind bitmap to canvas', 0),
  ('android.graphics', 'Canvas', 'setDrawFilter', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'Deprecated in Android; no equivalent in OH', 0),
  ('android.graphics', 'Canvas', 'getDrawFilter', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'Deprecated in Android; no equivalent in OH', 0),
  ('android.graphics', 'Canvas', 'getMaximumBitmapWidth', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No max bitmap dimension query in OH NDK', 0),
  ('android.graphics', 'Canvas', 'getMaximumBitmapHeight', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No max bitmap dimension query in OH NDK', 0),
  ('android.graphics', 'Canvas', 'drawPatch', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No patch drawing in OH NDK', 0),
  ('android.graphics', 'Canvas', 'clipRRect', 'native_drawing', 'OH_Drawing_Canvas', NULL, 4.0, 'No RRect clip; approximate via clipPath with round rect path', 0),
  ('android.graphics', 'Canvas', 'drawRegion', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No drawRegion in OH Drawing NDK', 0),
  ('android.graphics', 'Canvas', 'drawNinePatch', 'native_drawing', 'OH_Drawing_Canvas', NULL, 3.0, 'No nine-patch drawing in OH NDK', 0),
  ('android.graphics', 'Canvas', 'insertReorderBarrier', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'Internal; no equivalent', 0),
  ('android.graphics', 'Canvas', 'insertInorderBarrier', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'Internal; no equivalent', 0),
  ('android.graphics', 'Canvas', 'drawMesh', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No mesh drawing in OH NDK', 0),
  ('android.graphics', 'Canvas', 'punchHole', 'native_drawing', 'OH_Drawing_Canvas', NULL, 2.0, 'No punch hole in OH NDK', 0),
  ('android.graphics', 'Canvas', 'finalize', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDestroy', 8.0, 'Destroy canvas', 0),
  ('android.graphics', 'Canvas', 'drawTextBlob', 'native_drawing', 'OH_Drawing_Canvas', 'OH_Drawing_CanvasDrawTextBlob', 9.0, 'Direct mapping if TextBlob available', 0);

-- ============================================================
-- BATCH 5: Matrix (all 48 methods)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.graphics', 'Matrix', 'Matrix', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixCreate', 9.0, 'Constructor', 0),
  ('android.graphics', 'Matrix', 'isIdentity', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No isIdentity check in OH NDK; compare values', 0),
  ('android.graphics', 'Matrix', 'isAffine', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No isAffine check; inspect persp values', 0),
  ('android.graphics', 'Matrix', 'rectStaysRect', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No rectStaysRect in OH NDK', 0),
  ('android.graphics', 'Matrix', 'set', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Copy all 9 values via SetMatrix', 0),
  ('android.graphics', 'Matrix', 'reset', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set to identity values (1,0,0,0,1,0,0,0,1)', 0),
  ('android.graphics', 'Matrix', 'setTranslate', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set translate matrix via SetMatrix(1,0,tx,0,1,ty,0,0,1)', 0),
  ('android.graphics', 'Matrix', 'setScale', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set scale matrix via SetMatrix(sx,0,0,0,sy,0,0,0,1)', 0),
  ('android.graphics', 'Matrix', 'setRotate', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Compute cos/sin and set via SetMatrix', 0),
  ('android.graphics', 'Matrix', 'setSinCos', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set rotation via sin/cos values', 0),
  ('android.graphics', 'Matrix', 'setSkew', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set skew matrix via SetMatrix(1,kx,0,ky,1,0,0,0,1)', 0),
  ('android.graphics', 'Matrix', 'setConcat', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No matrix multiply in OH NDK; compute manually', 0),
  ('android.graphics', 'Matrix', 'preTranslate', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No pre-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'preScale', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No pre-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'preRotate', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No pre-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'preSkew', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No pre-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'preConcat', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No pre-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'postTranslate', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No post-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'postScale', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No post-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'postRotate', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No post-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'postSkew', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No post-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'postConcat', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No post-multiply; compute manually and SetMatrix', 0),
  ('android.graphics', 'Matrix', 'setRectToRect', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 6.0, 'Compute transform from src to dst rect; call SetMatrix', 0),
  ('android.graphics', 'Matrix', 'setPolyToPoly', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No poly-to-poly in OH NDK; compute affine manually', 0),
  ('android.graphics', 'Matrix', 'invert', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No matrix invert in OH NDK; compute manually', 0),
  ('android.graphics', 'Matrix', 'mapPoints', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No mapPoints in OH NDK; apply matrix transform manually', 0),
  ('android.graphics', 'Matrix', 'mapVectors', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No mapVectors in OH NDK; apply rotation/scale manually', 0),
  ('android.graphics', 'Matrix', 'mapRect', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'No mapRect in OH NDK; transform corners manually', 0),
  ('android.graphics', 'Matrix', 'mapRadius', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No mapRadius in OH NDK; compute from scale factors', 0),
  ('android.graphics', 'Matrix', 'getValues', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No getValues in OH NDK; track values externally', 0),
  ('android.graphics', 'Matrix', 'setValues', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 9.0, 'Direct mapping; pass all 9 float values', 0),
  ('android.graphics', 'Matrix', 'toString', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No toString; format from tracked values', 0),
  ('android.graphics', 'Matrix', 'toShortString', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No toShortString; format from tracked values', 0),
  ('android.graphics', 'Matrix', 'equals', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No equals in OH NDK; compare tracked values', 0),
  ('android.graphics', 'Matrix', 'hashCode', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No hashCode; compute from tracked values', 0),
  ('android.graphics', 'Matrix', 'dump', 'native_drawing', 'OH_Drawing_Matrix', NULL, 2.0, 'Debug only; no equivalent', 0),
  ('android.graphics', 'Matrix', 'finalize', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixDestroy', 8.0, 'Destroy matrix', 0),
  ('android.graphics', 'Matrix', 'isSimple', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No isSimple check; inspect values', 0),
  ('android.graphics', 'Matrix', 'obeysContractOfIsSimple', 'native_drawing', 'OH_Drawing_Matrix', NULL, 2.0, 'Internal; no equivalent', 0),
  ('android.graphics', 'Matrix', 'checkPointArrays', 'native_drawing', 'OH_Drawing_Matrix', NULL, 2.0, 'Internal validation; no equivalent', 0),
  ('android.graphics', 'Matrix', 'setAffine', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set affine transform via SetMatrix', 0),
  ('android.graphics', 'Matrix', 'isTranslate', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No isTranslate; check values', 0),
  ('android.graphics', 'Matrix', 'postMul', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'Compute matrix multiply manually', 0),
  ('android.graphics', 'Matrix', 'preMul', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'Compute matrix multiply manually', 0),
  ('android.graphics', 'Matrix', 'multiply', 'native_drawing', 'OH_Drawing_Matrix', NULL, 4.0, 'Compute matrix multiply manually', 0),
  ('android.graphics', 'Matrix', 'setScaleTranslate', 'native_drawing', 'OH_Drawing_Matrix', 'OH_Drawing_MatrixSetMatrix', 7.0, 'Set combined scale+translate', 0),
  ('android.graphics', 'Matrix', 'getType', 'native_drawing', 'OH_Drawing_Matrix', NULL, 3.0, 'No type flags in OH NDK; compute from values', 0),
  ('android.graphics', 'Matrix', 'MSCALE_X', 'native_drawing', 'OH_Drawing_Matrix', NULL, 8.0, 'Constant index 0; use directly', 0);

-- ============================================================
-- BATCH 6: Parcel (methods 1-50)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.os', 'Parcel', 'obtain', '@ohos.rpc', 'MessageSequence', 'create', 9.0, 'Factory method', 0),
  ('android.os', 'Parcel', 'recycle', '@ohos.rpc', 'MessageSequence', 'reclaim', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'dataSize', '@ohos.rpc', 'MessageSequence', 'getSize', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'dataCapacity', '@ohos.rpc', 'MessageSequence', 'getCapacity', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'dataAvail', '@ohos.rpc', 'MessageSequence', 'getReadableBytes', 8.0, 'Approximate: readable bytes remaining', 0),
  ('android.os', 'Parcel', 'dataPosition', '@ohos.rpc', 'MessageSequence', 'getReadPosition', 8.0, 'Read position; OH separates read/write positions', 0),
  ('android.os', 'Parcel', 'setDataSize', '@ohos.rpc', 'MessageSequence', 'setSize', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'setDataCapacity', '@ohos.rpc', 'MessageSequence', 'setCapacity', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'setDataPosition', '@ohos.rpc', 'MessageSequence', 'rewindRead', 7.0, 'OH uses rewindRead/rewindWrite; no arbitrary position set', 0),
  ('android.os', 'Parcel', 'writeByte', '@ohos.rpc', 'MessageSequence', 'writeByte', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeInt', '@ohos.rpc', 'MessageSequence', 'writeInt', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeLong', '@ohos.rpc', 'MessageSequence', 'writeLong', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeFloat', '@ohos.rpc', 'MessageSequence', 'writeFloat', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeDouble', '@ohos.rpc', 'MessageSequence', 'writeDouble', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeString', '@ohos.rpc', 'MessageSequence', 'writeString', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeBoolean', '@ohos.rpc', 'MessageSequence', 'writeBoolean', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeChar', '@ohos.rpc', 'MessageSequence', 'writeChar', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeShort', '@ohos.rpc', 'MessageSequence', 'writeShort', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readByte', '@ohos.rpc', 'MessageSequence', 'readByte', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readInt', '@ohos.rpc', 'MessageSequence', 'readInt', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readLong', '@ohos.rpc', 'MessageSequence', 'readLong', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readFloat', '@ohos.rpc', 'MessageSequence', 'readFloat', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readDouble', '@ohos.rpc', 'MessageSequence', 'readDouble', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readString', '@ohos.rpc', 'MessageSequence', 'readString', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readBoolean', '@ohos.rpc', 'MessageSequence', 'readBoolean', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readChar', '@ohos.rpc', 'MessageSequence', 'readChar', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readShort', '@ohos.rpc', 'MessageSequence', 'readShort', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeByteArray', '@ohos.rpc', 'MessageSequence', 'writeByteArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeIntArray', '@ohos.rpc', 'MessageSequence', 'writeIntArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeLongArray', '@ohos.rpc', 'MessageSequence', 'writeLongArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeFloatArray', '@ohos.rpc', 'MessageSequence', 'writeFloatArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeDoubleArray', '@ohos.rpc', 'MessageSequence', 'writeDoubleArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeStringArray', '@ohos.rpc', 'MessageSequence', 'writeStringArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeBooleanArray', '@ohos.rpc', 'MessageSequence', 'writeBooleanArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeCharArray', '@ohos.rpc', 'MessageSequence', 'writeCharArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeShortArray', '@ohos.rpc', 'MessageSequence', 'writeShortArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readByteArray', '@ohos.rpc', 'MessageSequence', 'readByteArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readIntArray', '@ohos.rpc', 'MessageSequence', 'readIntArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readLongArray', '@ohos.rpc', 'MessageSequence', 'readLongArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readFloatArray', '@ohos.rpc', 'MessageSequence', 'readFloatArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readDoubleArray', '@ohos.rpc', 'MessageSequence', 'readDoubleArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readStringArray', '@ohos.rpc', 'MessageSequence', 'readStringArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readBooleanArray', '@ohos.rpc', 'MessageSequence', 'readBooleanArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readCharArray', '@ohos.rpc', 'MessageSequence', 'readCharArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readShortArray', '@ohos.rpc', 'MessageSequence', 'readShortArray', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeStrongBinder', '@ohos.rpc', 'MessageSequence', 'writeRemoteObject', 8.0, 'Binder→RemoteObject; conceptual match', 0),
  ('android.os', 'Parcel', 'readStrongBinder', '@ohos.rpc', 'MessageSequence', 'readRemoteObject', 8.0, 'Binder→RemoteObject; conceptual match', 0),
  ('android.os', 'Parcel', 'writeFileDescriptor', '@ohos.rpc', 'MessageSequence', 'writeFileDescriptor', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readFileDescriptor', '@ohos.rpc', 'MessageSequence', 'readFileDescriptor', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeInterfaceToken', '@ohos.rpc', 'MessageSequence', 'writeInterfaceToken', 9.0, 'Direct mapping', 0);

-- ============================================================
-- BATCH 7: Parcel (methods 51-83)
-- ============================================================

INSERT OR REPLACE INTO known_mappings
  (android_package, android_type, android_method, oh_module, oh_type, oh_method, score_override, notes, paradigm_shift)
VALUES
  ('android.os', 'Parcel', 'enforceInterface', '@ohos.rpc', 'MessageSequence', 'readInterfaceToken', 8.0, 'Read and verify token; OH uses readInterfaceToken', 0),
  ('android.os', 'Parcel', 'writeNoException', '@ohos.rpc', 'MessageSequence', 'writeNoException', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'readException', '@ohos.rpc', 'MessageSequence', 'readException', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'writeParcelable', '@ohos.rpc', 'MessageSequence', 'writeParcelable', 8.0, 'OH uses Sequenceable interface instead of Parcelable', 1),
  ('android.os', 'Parcel', 'readParcelable', '@ohos.rpc', 'MessageSequence', 'readParcelable', 8.0, 'OH uses Sequenceable interface', 1),
  ('android.os', 'Parcel', 'writeParcelableArray', '@ohos.rpc', 'MessageSequence', 'writeParcelableArray', 8.0, 'OH uses Sequenceable arrays', 1),
  ('android.os', 'Parcel', 'readParcelableArray', '@ohos.rpc', 'MessageSequence', 'readParcelableArray', 8.0, 'OH uses Sequenceable arrays', 1),
  ('android.os', 'Parcel', 'writeValue', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No generic writeValue; must dispatch by type', 0),
  ('android.os', 'Parcel', 'readValue', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No generic readValue; must dispatch by type', 0),
  ('android.os', 'Parcel', 'writeList', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No writeList; serialize items individually', 0),
  ('android.os', 'Parcel', 'readList', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No readList; deserialize items individually', 0),
  ('android.os', 'Parcel', 'writeMap', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No writeMap; serialize key-value pairs individually', 0),
  ('android.os', 'Parcel', 'readMap', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No readMap; deserialize key-value pairs individually', 0),
  ('android.os', 'Parcel', 'writeBundle', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No Bundle concept; serialize as map of typed values', 0),
  ('android.os', 'Parcel', 'readBundle', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No Bundle concept; deserialize as map of typed values', 0),
  ('android.os', 'Parcel', 'writePersistableBundle', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No PersistableBundle; serialize as typed map', 0),
  ('android.os', 'Parcel', 'readPersistableBundle', '@ohos.rpc', 'MessageSequence', NULL, 4.0, 'No PersistableBundle; deserialize as typed map', 0),
  ('android.os', 'Parcel', 'writeSerializable', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No Java Serializable support; use Sequenceable', 1),
  ('android.os', 'Parcel', 'readSerializable', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No Java Serializable support; use Sequenceable', 1),
  ('android.os', 'Parcel', 'writeTypedList', '@ohos.rpc', 'MessageSequence', 'writeParcelableArray', 6.0, 'Write as Sequenceable array', 0),
  ('android.os', 'Parcel', 'readTypedList', '@ohos.rpc', 'MessageSequence', 'readParcelableArray', 6.0, 'Read as Sequenceable array', 0),
  ('android.os', 'Parcel', 'writeTypedArray', '@ohos.rpc', 'MessageSequence', 'writeParcelableArray', 7.0, 'Write as Sequenceable array', 0),
  ('android.os', 'Parcel', 'readTypedArray', '@ohos.rpc', 'MessageSequence', 'readParcelableArray', 7.0, 'Read as Sequenceable array', 0),
  ('android.os', 'Parcel', 'writeTypedObject', '@ohos.rpc', 'MessageSequence', 'writeParcelable', 7.0, 'Write single Sequenceable', 0),
  ('android.os', 'Parcel', 'readTypedObject', '@ohos.rpc', 'MessageSequence', 'readParcelable', 7.0, 'Read single Sequenceable', 0),
  ('android.os', 'Parcel', 'writeStrongInterface', '@ohos.rpc', 'MessageSequence', 'writeRemoteObject', 7.0, 'Write IInterface as RemoteObject', 0),
  ('android.os', 'Parcel', 'writeBinderList', '@ohos.rpc', 'MessageSequence', 'writeRemoteObjectArray', 7.0, 'Write list of RemoteObjects', 0),
  ('android.os', 'Parcel', 'readBinderList', '@ohos.rpc', 'MessageSequence', 'readRemoteObjectArray', 7.0, 'Read list of RemoteObjects', 0),
  ('android.os', 'Parcel', 'createByteArray', '@ohos.rpc', 'MessageSequence', 'readByteArray', 8.0, 'readByteArray returns new array', 0),
  ('android.os', 'Parcel', 'createIntArray', '@ohos.rpc', 'MessageSequence', 'readIntArray', 8.0, 'readIntArray returns new array', 0),
  ('android.os', 'Parcel', 'createLongArray', '@ohos.rpc', 'MessageSequence', 'readLongArray', 8.0, 'readLongArray returns new array', 0),
  ('android.os', 'Parcel', 'createFloatArray', '@ohos.rpc', 'MessageSequence', 'readFloatArray', 8.0, 'readFloatArray returns new array', 0),
  ('android.os', 'Parcel', 'createDoubleArray', '@ohos.rpc', 'MessageSequence', 'readDoubleArray', 8.0, 'readDoubleArray returns new array', 0),
  ('android.os', 'Parcel', 'createStringArray', '@ohos.rpc', 'MessageSequence', 'readStringArray', 8.0, 'readStringArray returns new array', 0),
  ('android.os', 'Parcel', 'createBooleanArray', '@ohos.rpc', 'MessageSequence', 'readBooleanArray', 8.0, 'readBooleanArray returns new array', 0),
  ('android.os', 'Parcel', 'createCharArray', '@ohos.rpc', 'MessageSequence', 'readCharArray', 8.0, 'readCharArray returns new array', 0),
  ('android.os', 'Parcel', 'hasFileDescriptors', '@ohos.rpc', 'MessageSequence', 'containFileDescriptors', 9.0, 'Direct mapping', 0),
  ('android.os', 'Parcel', 'marshall', '@ohos.rpc', 'MessageSequence', 'writeRawData', 5.0, 'Approximate: serialize to raw bytes', 0),
  ('android.os', 'Parcel', 'unmarshall', '@ohos.rpc', 'MessageSequence', 'readRawData', 5.0, 'Approximate: deserialize from raw bytes', 0),
  ('android.os', 'Parcel', 'appendFrom', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No appendFrom; read and re-write data manually', 0),
  ('android.os', 'Parcel', 'writeRawFileDescriptor', '@ohos.rpc', 'MessageSequence', 'writeFileDescriptor', 7.0, 'OH does not distinguish raw vs managed FDs', 0),
  ('android.os', 'Parcel', 'readRawFileDescriptor', '@ohos.rpc', 'MessageSequence', 'readFileDescriptor', 7.0, 'OH does not distinguish raw vs managed FDs', 0),
  ('android.os', 'Parcel', 'writeSparseBooleanArray', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No SparseBooleanArray; serialize as int-boolean pairs', 0),
  ('android.os', 'Parcel', 'readSparseBooleanArray', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No SparseBooleanArray; deserialize as int-boolean pairs', 0),
  ('android.os', 'Parcel', 'writeSparseArray', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No SparseArray; serialize as key-value pairs', 0),
  ('android.os', 'Parcel', 'readSparseArray', '@ohos.rpc', 'MessageSequence', NULL, 3.0, 'No SparseArray; deserialize as key-value pairs', 0),
  ('android.os', 'Parcel', 'writeSize', '@ohos.rpc', 'MessageSequence', NULL, 5.0, 'Write width+height as two ints', 0),
  ('android.os', 'Parcel', 'readSize', '@ohos.rpc', 'MessageSequence', NULL, 5.0, 'Read width+height as two ints', 0),
  ('android.os', 'Parcel', 'writeSizeF', '@ohos.rpc', 'MessageSequence', NULL, 5.0, 'Write width+height as two floats', 0),
  ('android.os', 'Parcel', 'readSizeF', '@ohos.rpc', 'MessageSequence', NULL, 5.0, 'Read width+height as two floats', 0);
