// SPDX-License-Identifier: Apache-2.0
//
// ===========================================================================
// V2-Step3 (CR28-builder, 2026-05-13): WestlakeApplication
// ---------------------------------------------------------------------------
// Shadowed via scripts/framework_duplicates.txt: `android/app/Application` has
// been REMOVED from the strip list, so this class wins on classpath over the
// real framework.jar `android.app.Application`. See:
//   docs/engine/BINDER_PIVOT_DESIGN_V2.md §3.2 (decision 9-C classpath shadow)
//   docs/engine/BINDER_PIVOT_DESIGN_V2.md §7 Step 3 (this step)
//
// Class hierarchy the user's app sees:
//
//     Hilt_NoiceApplication        // generated by Hilt
//          extends NoiceApplication
//                   extends Application   <-- THIS CLASS (Westlake-owned)
//                            extends ContextWrapper
//                                       extends Context  (framework.jar)
//
// We DELIBERATELY do NOT extend the real framework.jar Application because
// the real Application class has cold-init expectations (ActivityThread,
// LoadedApk, PackageInfo) that we cannot satisfy without system_server
// bootstrap. This class satisfies the API surface that AOSP framework +
// AndroidX + Hilt + the user's app actually call.
//
// Compile-time vs runtime class graph (same trick CR23-fix / WestlakeContextImpl
// already use for `Context` and that Step 2 will extend for `Activity`):
//   Compile-time: extends shim's `android.content.ContextWrapper` (the shim
//                 file we ship under shim/java/android/content/ContextWrapper.java)
//   Runtime:     extends framework.jar's real `android.content.ContextWrapper`
//                (because ContextWrapper IS in framework_duplicates.txt and
//                 the shim copy is stripped from aosp-shim.dex; framework.jar
//                 wins class resolution).
//
// What stays minimal (per V2 spec):
//   - NO system_server bootstrap state (LoadedApk, ApplicationLoaders, etc.)
//   - NO ContextImpl internals
//   - NO per-app branches
//   - NO Hilt-specific obfuscated accessors (Hilt uses generic reflective
//     componentManager() lookup which our omission gracefully degrades; the
//     framework.jar Application also doesn't ship that method).
//
// What we DO ship:
//   - The 20 ActivityLifecycleCallbacks pre/main/post variants (AOSP API 30)
//   - The OnProvideAssistDataListener interface
//   - Package-private dispatchActivityXxx hooks for WestlakeActivity (Step 2)
//     to invoke from its perform* lifecycle methods
//   - ComponentCallbacks2 surface (onConfigurationChanged / onLowMemory /
//     onTrimMemory) since real framework's Application implements
//     ComponentCallbacks2; some apps register listeners that expect this
//   - registerActivityLifecycleCallbacks / registerComponentCallbacks /
//     registerOnProvideAssistDataListener
//   - attach(Context) — package-private hook called by ActivityThread to
//     seed mBase before onCreate()
//   - V1-compat: deprecated package-private setPackageName(String) so the
//     V1-era ShimCompat.setPackageName direct call (which is in a try/catch
//     anyway) doesn't fail compile. To be deleted with V1 MiniServer.
//
// Author: CR28-builder (V2-Step3)  Date: 2026-05-13

package android.app;

import android.content.ComponentCallbacks;
import android.content.ComponentCallbacks2;
import android.content.Context;
import android.content.ContextWrapper;
import android.content.res.Configuration;
import android.os.Bundle;

import java.util.ArrayList;

public class Application extends ContextWrapper implements ComponentCallbacks2 {

    private static final String TAG = "Application";

    /**
     * ActivityLifecycleCallbacks — AOSP API 30 surface. Includes the pre/post
     * variants added in API 29 (Q) so AndroidX libraries that probe for them
     * via reflection or override them via interface-default still bind.
     */
    public interface ActivityLifecycleCallbacks {

        default void onActivityPreCreated(Activity activity, Bundle savedInstanceState) {
        }

        void onActivityCreated(Activity activity, Bundle savedInstanceState);

        default void onActivityPostCreated(Activity activity, Bundle savedInstanceState) {
        }

        default void onActivityPreStarted(Activity activity) {
        }

        void onActivityStarted(Activity activity);

        default void onActivityPostStarted(Activity activity) {
        }

        default void onActivityPreResumed(Activity activity) {
        }

        void onActivityResumed(Activity activity);

        default void onActivityPostResumed(Activity activity) {
        }

        default void onActivityPrePaused(Activity activity) {
        }

        void onActivityPaused(Activity activity);

        default void onActivityPostPaused(Activity activity) {
        }

        default void onActivityPreStopped(Activity activity) {
        }

        void onActivityStopped(Activity activity);

        default void onActivityPostStopped(Activity activity) {
        }

        default void onActivityPreSaveInstanceState(Activity activity, Bundle outState) {
        }

        void onActivitySaveInstanceState(Activity activity, Bundle outState);

        default void onActivityPostSaveInstanceState(Activity activity, Bundle outState) {
        }

        default void onActivityPreDestroyed(Activity activity) {
        }

        void onActivityDestroyed(Activity activity);

        default void onActivityPostDestroyed(Activity activity) {
        }
    }

    /**
     * OnProvideAssistDataListener — apps that integrate with the Assist
     * subsystem call registerOnProvideAssistDataListener(...). We register
     * but never invoke (no Assist machinery in Westlake yet).
     */
    public interface OnProvideAssistDataListener {
        void onProvideAssistData(Activity activity, Bundle data);
    }

    // ---------------- instance state ----------------
    //
    // Surface kept intentionally small. The V1 hacks (mPackageName override,
    // MiniServer-routed lookups, Hilt-obfuscated b()/componentManager()
    // accessors) are gone: framework.jar's ContextWrapper.getPackageName()
    // already delegates to mBase, which our WestlakeContextImpl provides.

    private final ArrayList<ComponentCallbacks> mComponentCallbacks = new ArrayList<>();
    private final ArrayList<ActivityLifecycleCallbacks> mActivityLifecycleCallbacks =
            new ArrayList<>();
    private ArrayList<OnProvideAssistDataListener> mAssistCallbacks = null;

    public Application() {
        // mBase set later via attach(Context) -> attachBaseContext(Context).
        super(null);
    }

    /**
     * Called when the application is starting, before any activity, service,
     * or receiver objects (excluding content providers) have been created.
     *
     * Subclasses override to do init; default is a no-op. The user's
     * `Hilt_*Application.onCreate()` calls `super.onCreate()` (reaches here)
     * then fires Hilt's @Inject component build.
     */
    public void onCreate() {
    }

    /**
     * Emulated process environments only. Never called on a production Android
     * device (processes are removed by killing them).
     */
    public void onTerminate() {
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        Object[] callbacks = collectComponentCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ComponentCallbacks) cb).onConfigurationChanged(newConfig);
            }
        }
    }

    @Override
    public void onLowMemory() {
        Object[] callbacks = collectComponentCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ComponentCallbacks) cb).onLowMemory();
            }
        }
    }

    @Override
    public void onTrimMemory(int level) {
        Object[] callbacks = collectComponentCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                if (cb instanceof ComponentCallbacks2) {
                    ((ComponentCallbacks2) cb).onTrimMemory(level);
                }
            }
        }
    }

    public void registerComponentCallbacks(ComponentCallbacks callback) {
        if (callback == null) return;
        synchronized (mComponentCallbacks) {
            mComponentCallbacks.add(callback);
        }
    }

    public void unregisterComponentCallbacks(ComponentCallbacks callback) {
        if (callback == null) return;
        synchronized (mComponentCallbacks) {
            mComponentCallbacks.remove(callback);
        }
    }

    public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        if (callback == null) return;
        synchronized (mActivityLifecycleCallbacks) {
            mActivityLifecycleCallbacks.add(callback);
        }
    }

    public void unregisterActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        if (callback == null) return;
        synchronized (mActivityLifecycleCallbacks) {
            mActivityLifecycleCallbacks.remove(callback);
        }
    }

    public void registerOnProvideAssistDataListener(OnProvideAssistDataListener callback) {
        if (callback == null) return;
        synchronized (this) {
            if (mAssistCallbacks == null) {
                mAssistCallbacks = new ArrayList<>();
            }
            mAssistCallbacks.add(callback);
        }
    }

    public void unregisterOnProvideAssistDataListener(OnProvideAssistDataListener callback) {
        if (callback == null) return;
        synchronized (this) {
            if (mAssistCallbacks != null) {
                mAssistCallbacks.remove(callback);
            }
        }
    }

    /**
     * Returns the name of the current process. Real framework consults
     * ActivityThread.currentProcessName(); we have no process-name plumbing in
     * Westlake yet, so return null. Apps that NPE on this are using assistive
     * API and can be fixed by surfacing a process name (separate work).
     */
    public static String getProcessName() {
        return null;
    }

    // ---------------- internal hooks ----------------

    /**
     * Package-private attach hook. AOSP's `Application.attach(Context)` calls
     * `attachBaseContext(context)` then `mLoadedApk = ContextImpl.getImpl(context).mPackageInfo`.
     *
     * The second line is the cold-init drift V2 §1.4 explicitly avoids: it
     * assumes `context` is a real `ContextImpl` (we ship `WestlakeContextImpl`,
     * which deliberately is not), so we only do the first line. Apps that try
     * to reach `mLoadedApk` reflectively will see null; on real Android most
     * apps use `getApplicationContext()` / `getPackageManager()` instead and
     * those reach our `mBase` correctly.
     *
     * Called by `WestlakeActivityThread.makeApplication` /
     * `WestlakeLauncher.primeAllocatedApplication`.
     */
    /* package */ final void attach(Context base) {
        attachBaseContext(base);
    }

    // ---------------- dispatchActivityXxx hooks ----------------
    //
    // Package-private because AOSP's `ActivityThread.handleLaunchActivity` etc.
    // call these as the Activity lifecycle progresses. Our equivalent
    // (`WestlakeActivity.performCreate` / `performStart` / ... — Step 2)
    // will call these from the same package.

    /* package */ void dispatchActivityPreCreated(Activity activity, Bundle savedInstanceState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreCreated(activity, savedInstanceState);
            }
        }
    }

    /* package */ void dispatchActivityCreated(Activity activity, Bundle savedInstanceState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityCreated(activity, savedInstanceState);
            }
        }
    }

    /* package */ void dispatchActivityPostCreated(Activity activity, Bundle savedInstanceState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostCreated(activity, savedInstanceState);
            }
        }
    }

    /* package */ void dispatchActivityPreStarted(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreStarted(activity);
            }
        }
    }

    /* package */ void dispatchActivityStarted(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityStarted(activity);
            }
        }
    }

    /* package */ void dispatchActivityPostStarted(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostStarted(activity);
            }
        }
    }

    /* package */ void dispatchActivityPreResumed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreResumed(activity);
            }
        }
    }

    /* package */ void dispatchActivityResumed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityResumed(activity);
            }
        }
    }

    /* package */ void dispatchActivityPostResumed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostResumed(activity);
            }
        }
    }

    /* package */ void dispatchActivityPrePaused(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPrePaused(activity);
            }
        }
    }

    /* package */ void dispatchActivityPaused(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPaused(activity);
            }
        }
    }

    /* package */ void dispatchActivityPostPaused(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostPaused(activity);
            }
        }
    }

    /* package */ void dispatchActivityPreStopped(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreStopped(activity);
            }
        }
    }

    /* package */ void dispatchActivityStopped(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityStopped(activity);
            }
        }
    }

    /* package */ void dispatchActivityPostStopped(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostStopped(activity);
            }
        }
    }

    /* package */ void dispatchActivityPreSaveInstanceState(Activity activity, Bundle outState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreSaveInstanceState(activity, outState);
            }
        }
    }

    /* package */ void dispatchActivitySaveInstanceState(Activity activity, Bundle outState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivitySaveInstanceState(activity, outState);
            }
        }
    }

    /* package */ void dispatchActivityPostSaveInstanceState(Activity activity, Bundle outState) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostSaveInstanceState(activity, outState);
            }
        }
    }

    /* package */ void dispatchActivityPreDestroyed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPreDestroyed(activity);
            }
        }
    }

    /* package */ void dispatchActivityDestroyed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityDestroyed(activity);
            }
        }
    }

    /* package */ void dispatchActivityPostDestroyed(Activity activity) {
        Object[] callbacks = collectActivityLifecycleCallbacks();
        if (callbacks != null) {
            for (Object cb : callbacks) {
                ((ActivityLifecycleCallbacks) cb).onActivityPostDestroyed(activity);
            }
        }
    }

    /* package */ void dispatchOnProvideAssistData(Activity activity, Bundle data) {
        Object[] callbacks;
        synchronized (this) {
            if (mAssistCallbacks == null) {
                return;
            }
            callbacks = mAssistCallbacks.toArray();
        }
        for (Object cb : callbacks) {
            ((OnProvideAssistDataListener) cb).onProvideAssistData(activity, data);
        }
    }

    private Object[] collectComponentCallbacks() {
        Object[] callbacks = null;
        synchronized (mComponentCallbacks) {
            if (mComponentCallbacks.size() > 0) {
                callbacks = mComponentCallbacks.toArray();
            }
        }
        return callbacks;
    }

    private Object[] collectActivityLifecycleCallbacks() {
        Object[] callbacks = null;
        synchronized (mActivityLifecycleCallbacks) {
            if (mActivityLifecycleCallbacks.size() > 0) {
                callbacks = mActivityLifecycleCallbacks.toArray();
            }
        }
        return callbacks;
    }

    // ---------------- V1 backward-compat shim ----------------
    //
    // V1's MiniServer / ShimCompat path calls `setPackageName(String)` directly
    // on Application (wrapped in try/catch in ShimCompat, so it can fall back
    // to reflection on real Android where this method does not exist). javac
    // still needs the method to exist at compile time. This is a deliberate
    // V1 hangover that will be deleted alongside MiniServer once the V2
    // substrate (Steps 2 + 6) replaces the MiniServer-based cold-boot path.
    //
    // DO NOT add new callers. The package-name lookup at runtime should go
    // through mBase (our WestlakeContextImpl) via ContextWrapper.getPackageName.
    @Deprecated
    /* package */ void setPackageName(String pkg) {
        // No-op: getPackageName() delegates to mBase via ContextWrapper.
    }
}
